CREATE TABLE TRADE(
	TRANSACTIONNUM NUMBER NOT NULL,
	ACCOUNTNUM VARCHAR2(200) NOT NULL,
	TRADEMOUNT DATE NOT NULL,
	TRADEKIND NUMBER(1) NOT NULL,
	TRADEBALANCE NUMBER NOT NULL,
	TRADEDATE DATE NOT NULL,
	
	CONSTRAINT PK_INFO_TRANSACTION_NO PRIMARY KEY (TRANSACTIONNUM)

);

ALTER TABLE TRADE ADD CONSTRAINT FK_TRADE_ACCOUNTNUM FOREIGN KEY (ACCOUNTNUM) REFERENCES ACCOUNTS(ACCOUNTNUM);

COMMENT ON COLUMN TRADE.TRANSACTIONNUM  IS '거래번호';
COMMENT ON COLUMN TRADE.ACCOUNTNUM  IS '계좌번호';
COMMENT ON COLUMN TRADE.TRADEMOUNT  IS '금액';
COMMENT ON COLUMN TRADE.TRADEKIND  IS '거래구분';
COMMENT ON COLUMN TRADE.TRADEBALANCE  IS '잔액';
COMMENT ON COLUMN TRADE.TRADEDATE  IS '거래일시';

--DROP TABLE TRADE;

ALTER TABLE TRADE DROP COLUMN TRADEMOUNT;
ALTER TABLE TRADE ADD (TRADEMOUNT NUMBER NOT NULL);

CREATE TABLE ACCOUNTS (
	ACCOUNTNUM VARCHAR2(200) NOT NULL,
	PRODUCTNUM NUMBER NOT NULL,
	USER_NAME VARCHAR2(200) NOT NULL,
	ACCOUNTSBALANCE NUMBER NOT NULL,
	ACCOUNTDATE DATE NOT NULL,
	
	CONSTRAINT PK_ACCOUNTS_TRANSACTION_NO PRIMARY KEY (ACCOUNTNUM)
);

DROP 
COMMENT ON COLUMN ACCOUNTS.ACCOUNTNUM IS '계좌번호';
COMMENT ON COLUMN ACCOUNTS.PRODUCTNUM IS '상품번호';
COMMENT ON COLUMN ACCOUNTS.USER_NAME IS '회원아이디';
COMMENT ON COLUMN ACCOUNTS.ACCOUNTSBALANCE IS '잔액';
COMMENT ON COLUMN ACCOUNTS.ACCOUNTDATE IS '가입일';

ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACCOUNTS_PRODUCTNUM FOREIGN KEY (PRODUCTNUM) REFERENCES PRODUCTS(PRODUCTNUM);
ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACCOUNTS_USER_NAME FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME);

--DROP TABLE ACCOUNTS;

CREATE TABLE PRODUCTS (
	PRODUCTNUM NUMBER NOT NULL,
	PRODUCTNAME VARCHAR2(200) NOT NULL,
	PRODUCTDETAIL CLOB NOT NULL,
	PRODUCTRATE NUMBER(4,2) NOT NULL,
	PRODUCTDATE DATE NOT NULL,
	
	CONSTRAINT PK_GIFTS_GIFT_CODE PRIMARY KEY (PRODUCTNUM)
);

--ALTER TABLE PRODUCTS DROP COLUMN GIFT_NM;
--ALTER TABLE PRODUCTS ADD (GIFT_NM VARCHAR2(30) NOT NULL UNIQUE);

--DROP TABLE GIFTS;
--ALTER TABLE GIFTS DROP COLUMN GIFT_CG;

COMMENT ON COLUMN PRODUCTS.PRODUCTNUM IS '상품번호';
COMMENT ON COLUMN PRODUCTS.PRODUCTNAME IS '상품이름';
COMMENT ON COLUMN PRODUCTS.PRODUCTDETAIL IS '상품상세설명';
COMMENT ON COLUMN PRODUCTS.PRODUCTRATE IS '이자율';
COMMENT ON COLUMN PRODUCTS.PRODUCTDATE IS '기간';
--COMMENT ON COLUMN GIFTS.GIFT_CG IS '상품유형';

CREATE TABLE USERS(
	USER_NAME VARCHAR2(200) NOT NULL,
	PASSWORD VARCHAR2(200) NOT NULL,
	NAME VARCHAR2(200) NOT NULL,
	PHONE VARCHAR2(200) NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	
	CONSTRAINT PK_USERS_USER_ID PRIMARY KEY (USER_NAME)

);

--ALTER TABLE USERS RENAME COLUMN OIN_DATE TO JOIN_DATE;

COMMENT ON COLUMN USERS.USER_NAME IS '회원아이디';
COMMENT ON COLUMN USERS.PASSWORD IS '비밀번호';
COMMENT ON COLUMN USERS.NAME IS '이름';
COMMENT ON COLUMN USERS.PHONE IS '전화번호';
COMMENT ON COLUMN USERS.EMAIL IS '이메일';

--DROP TABLE USERS;

CREATE TABLE CARTS (
	USER_NAME VARCHAR2(200) NOT NULL,
	PRODUCTNUM NUMBER NOT NULL,
	
	CONSTRAINT FK_CARTS_USER_NAME FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME),
	CONSTRAINT FK_CARTS_PRODUCTNUM FOREIGN KEY (PRODUCTNUM) REFERENCES PRODUCTS(PRODUCTNUM)
	
);

ALTER TABLE CARTS DROP CONSTRAINT FK_CARTS_USER_NAME;
ALTER TABLE CARTS DROP CONSTRAINT FK_CARTS_PRODUCTNUM;

ALTER TABLE CARTS ADD CONSTRAINT PK_CARTS_USER_PRNUM PRIMARY KEY (USER_NAME, PRODUCTNUM);


COMMENT ON COLUMN CARTS.USER_NAME IS '회원아이디';
COMMENT ON COLUMN CARTS.PRODUCTNUM IS '상품번호';


INSERT INTO TRADE
VALUES (1,'12345-02-67890',1,20000,'20240122',20000);

INSERT INTO ACCOUNTS
VALUES ('12345-02-67890',1,'LEE7365',20000,'20240502');

INSERT INTO PRODUCTS
VALUES (1,'부자적금','이상품에 가입하면 부자가 될수 있습니다.',9.12,'20251225');

INSERT INTO USERS
VALUES ('LEE1234','ABCD1234', '이민열','010-1234-5678','LEE@NAVER.COM');

INSERT INTO CARTS
VALUES ('LEE1234', 1);
